export interface AcopioList{
    id: number,
    fechadoc:Date,
    fechaing:Date,
    fechaolp:Date,
    doc:string,
    num_doc:string,
    serie:string,
    numero:string,
    cod_acopio:number,
    dni:string,
    datos:string,
    tipos:string,
    transaccion:string,
    banco:string,
    num_banco:string,
    moneda:string,
    cantidad:number,
    pago:number,
    neto:number,
    dscto:number,
    flete:string,
    total:number,
    estado:string,
    usuario:string
}