export interface Partner {
    id:string,
    dni: string,
    nombre: string,
    estado: string,
    fechanaci: Date,
    estadocivil: string,
    gradoinstruccion: string,
    telefono: string,
    comitesectorial: string,
    entidadbancaria: string,
    nrocuenta: string,
    email: string,
    residencia: string,
    localidad: string,
    distrito: string,
    provincia: string,
    departamento: string,
    beneficiario: string,
    dnibeneficiario: string,
    estadodelpredio: string,
    dniconyuge: string,
    nombreconyuge: string,
    tecnico: string
}